#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9
yabai -m config status_bar_power_icon_strip  ? ?
yabai -m config status_bar_space_icon        ?
yabai -m config status_bar_clock_icon        ?

find "${TMPDIR}" -type f -perm +111 -name "yabai_${USER}_monocle_mode_*" -delete

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.1
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   10

# yabai -m rule --add title='^Activity Monitor .*' manage=off topmost=on
# yabai -m rule --add title='^Wireless Diagnostics$' manage=off topmost=on
# yabai -m rule --add title='Privacy$' manage=off topmost=on
# yabai -m rule --add title='Dock' manage=off topmost=on
# yabai -m rule --add title='Reminders' manage=off topmost=on
# yabai -m rule --add title='.*Exchange.*' manage=off topmost=on
# yabai -m rule --add title='Ukelele' manage=off topmost=on

# Exclude by default
yabai -m rule --add app='.*' manage=off

# # Add applications to tile.

yabai -m rule --add app='^iTerm2$' role="AXWindow" subrole="AXStandardWindow" manage=on topmost=off
yabai -m rule --add app='^Google Chrome$' role="AXWindow" subrole="AXStandardWindow" manage=on topmost=off
yabai -m rule --add app='^Code$' role="AXWindow" subrole="AXStandardWindow" manage=on topmost=off
yabai -m rule --add app='^Safari$' role="AXWindow" subrole="AXStandardWindow" manage=on topmost=off

# Remove preferences from launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"those apps


echo "yabai configuration loaded.."
