#!/bin/sh

bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')

VOL_BEFORE=$(amixer -c 0 sget Master | grep % | awk '{ print $4}' | sed -e 's/[]*%*[*]//g')

if [ $VOL_BEFORE -ne 0 ]
  then
    amixer -q -c 0 -- sset Master playback 2- unmute
    VOL_NEW=$(amixer -c 0 sget Master | grep % | awk '{ print $4}' | sed -e 's/[]*%*[*]//g')
    notify-send -h "int:value:$VOL_NEW" "Volume" "Master: "
fi

 
